### ISSUE TITLE
Roadmap: simplify

### ISSUE THREAD

**Issue by paulrgn** [dadi/cloud#87]
- [x] Make timeline the index, kill article view (current roadmap index)
- [x] Option to link to articles from roadmap milestones
- [x] Consider where timeline starts; how to navigate between future and past
